version: '3'
services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - REDIS_HOST=redis
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    expose:
      - 6379
    restart: always
