from flask import Flask, request
import time

app = Flask(__name__)

@app.route('/invoke', methods=['POST'])
def generate():
    request_json = request.json
    text = request_json['input']
    time.sleep(1)
    if 's3_upload_fields' in request_json:
        result = f'https://cdn.clustro.ai/generated-data/test.png'
    else:
        result = f'{text} ... some more text generated by model.'
    return result

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
