FROM gcr.io/datadoghq/agent:latest
ADD conf.d/redisdb.yaml /etc/datadog-agent/conf.d/redisdb.yaml
ADD conf.d/frontend.yaml /etc/datadog-agent/conf.d/frontend.yaml
ADD conf.d/nginx.yaml /etc/datadog-agent/conf.d/nginx.yaml
ADD conf.d/backend.yaml /etc/datadog-agent/conf.d/backend.yaml
